name: build
on: pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          stable: true
      - name: Download go modules
        run: go mod download
      - name: Go build
        run: go build -o /dev/null ./...