name: build
on: pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          stable: true
      - name: Download go modules
        run: go mod download
      - name: Go build
        run: go build -o /dev/null ./...