name: releaser

on:
  push:
    tags:
      - '*'

jobs:
  releaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v4
      - 
        uses: izumin5210/action-go-crossbuild@releases/v1
        with:
          package: ./cmd/xlsx-spf
      - 
        uses: softprops/action-gh-release@v2
        with:
          files: './dist/*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: startsWith(github.ref, 'refs/tags/')
      - 
        uses: izumin5210/action-homebrew@releases/v0
        with:
          tap: cobraz/homebrew-tools
          token: ${{ secrets.GITHUB_TOKEN }}
          tap-token: ${{ secrets.TAP_GITHUB_TOKEN }}