name: create tag

on:
  push:
    branches:
      - master
      
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - uses: go-semantic-release/action@v1
      with:
        github-token: ${{ secrets.TAP_GITHUB_TOKEN }}