name: create tag

on:
  push:
    branches:
      - master
      
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
    - uses: go-semantic-release/action@v1
      with:
        github-token: ${{ secrets.TAP_GITHUB_TOKEN }}